- name: install ufw
  apt:
    pkg:
      - ufw
    state: present

# TODO: Possibly update /etc/services for easier administration
- name: allow ports for application
  ufw:
    rule: allow
    port: "{{ item.value.port }}"
    proto: "{{ item.value.protocol }}"
  with_dict: "{{ ufw_ports }}"
  notify: reload ufw

- name: enable ufw logging
  ufw:
    logging: low

- name: lock down all ports by default
  ufw:
    default: reject
    direction: incoming
    state: enabled
