- hosts: all
  gather_facts: false
  vars:
    state: present
    force: false
    docker_port: 2376
    docker_config_directory: ~/.config/docker
  tasks:
    - name: "{{ 'start' if state == 'present' else 'stop' }} applications"
      docker_compose:
        docker_host: "tcp://{{ inventory_hostname }}:{{ docker_port }}"
        project_src: ./apps
        validate_certs: true
        client_cert: "{{ docker_config_directory }}/cert.pem"
        client_key: "{{ docker_config_directory }}/key.pem"
        hostname_check: true
        tls_hostname: "{{ inventory_hostname }}"
        remove_orphans: true
        pull: true
        build: true
        nocache: "{{ force }}"
        state: "{{ state }}"
      delegate_to: localhost
      register: compose_output
      environment:
        - CADDY_ADMIN_USER_PASSWORD_HASH: "{{ admin_user_password_hash }}"
        - CADDY_ADMIN_USER_SALT: "{{ admin_user_salt }}"

    - name: prune dangling images
      docker_prune:
        docker_host: "tcp://{{ inventory_hostname }}:{{ docker_port }}"
        validate_certs: true
        client_cert: "{{ docker_config_directory }}/cert.pem"
        client_key: "{{ docker_config_directory }}/key.pem"
        tls_hostname: "{{ inventory_hostname }}"
        images: true
      delegate_to: localhost
      when: compose_output.changed
