version: "3"
services:
  murmur:
    build: ./apps/murmur
    restart: unless-stopped
    ports:
      - "1337:64738"
      - "1337:64738/udp"
    volumes:
      - /etc/letsencrypt:/data/certs:ro
      - /data/murmur:/data/db:rw

  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    expose:
      - "8384"
    ports:
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - /data/syncthing:/var/syncthing:rw

  caddy:
    build: ./apps/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_cache:/data:rw
      - /etc/letsencrypt:/certs:ro
      - /data/syncthing:/usr/share/caddy:ro
    environment:
      - CADDY_ADMIN_USER_PASSWORD_HASH
      - CADDY_ADMIN_USER_SALT
    depends_on:
      - syncthing
volumes:
  caddy_cache:
