version: "3"
services:
  murmur:
    build: ./apps/murmur
    restart: unless-stopped
    ports:
      - "${MURMUR_UDP_PORT:?}:64738/udp"
    volumes:
      - murmur_cache:/data/cache:rw
      - /data/murmur:/data/db:rw

  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "${SYNCTHING_PORT:?}:22000"
      - "${SYNCTHING_DISCOVERY_PORT:?}:21027/udp"
    volumes:
      - /data/syncthing:/var/syncthing:rw
  
  gh:
    build: ./apps/gh
    restart: unless-stopped

  caddy:
    build: ./apps/caddy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:?}:80"
      - "${HTTPS_PORT:?}:443"
      - "${MURMUR_PORT:?}:64738"
    volumes:
      - caddy_cache:/data:rw
      - /data/syncthing:/usr/share/caddy:ro
    env_file: .env
    depends_on:
      - gh
      - murmur
      - syncthing
volumes:
  caddy_cache:
  murmur_cache:
