version: "3"
services:
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "${SYNCTHING_PORT:?}:22000"
      - "${SYNCTHING_DISCOVERY_PORT:?}:21027/udp"
    volumes:
      - /data/syncthing:/var/syncthing:rw
    depends_on:
      - caddy
    command: -logflags=0

  gh:
    build: ./apps/gh
    restart: unless-stopped
    depends_on:
      - caddy

  caddy:
    build: ./apps/caddy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:?}:80"
      - "${HTTPS_PORT:?}:443"
    volumes:
      - caddy_cache:/data:rw
      - /data/syncthing:/usr/share/caddy:ro
    tmpfs: /config
    env_file: .env

  # Monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.5
    command: --docker_only=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    build: ./apps/prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /data/prometheus:/prometheus:rw

volumes:
  caddy_cache:
