version: "3"
services:
  murmur:
    build: ./apps/murmur
    restart: unless-stopped
    ports:
      - "${MURMUR_PORT:?}:64738"
      - "${MURMUR_UDP_PORT:?}:64738/udp"
    volumes:
      - /etc/letsencrypt:/data/certs:ro
      - /data/murmur:/data/db:rw

  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "${SYNCTHING_PORT:?}:22000"
      - "${SYNCTHING_DISCOVERY_PORT:?}:21027/udp"
    volumes:
      - /data/syncthing:/var/syncthing:rw
  
  gh:
    build: ./apps/gh
    restart: unless-stopped

  caddy:
    build: ./apps/caddy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:?}:80"
      - "${HTTPS_PORT:?}:443"
    volumes:
      - caddy_cache:/data:rw
      - /etc/letsencrypt:/certs:ro
      - /data/syncthing:/usr/share/caddy:ro
    environment:
      - CADDY_ADMIN_USER_PASSWORD_HASH=${CADDY_ADMIN_USER_PASSWORD_HASH:?}
      - CADDY_ADMIN_USER_SALT=${CADDY_ADMIN_USER_SALT:?}
      - MAIN_DOMAIN=${MAIN_DOMAIN:?}
      - GH_DOMAIN_ALIAS=${GH_DOMAIN_ALIAS:?}
    depends_on:
      - gh
      - syncthing
volumes:
  caddy_cache:
