version: "3"
services:
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "${SYNCTHING_PORT:?}:22000"
      - "${SYNCTHING_DISCOVERY_PORT:?}:21027/udp"
    volumes:
      - /data/syncthing:/var/syncthing:rw
    depends_on:
      - caddy
    command: -logflags=0
  
  gh:
    build: ./apps/gh
    restart: unless-stopped
    depends_on:
      - caddy

  caddy:
    build: ./apps/caddy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:?}:80"
      - "${HTTPS_PORT:?}:443"
    volumes:
      - caddy_cache:/data:rw
      - /data/syncthing:/usr/share/caddy:ro
    tmpfs: /config
    env_file: .env
volumes:
  caddy_cache:
