#! /usr/bin/ansible-playbook
- name: minimal server setup
  hosts: app
  become: true
  tags: bootstrap
  vars:
    ssh_ca_private_key_path: ~/.ssh/ca/ssh_ca
    ssh_ca_public_key_path: "{{ ssh_ca_private_key_path }}.pub"
  roles:
    - create_ansible_user
    - trust_ssh_ca
    - sign_host_keys
    - secure_access

- name: full app server setup
  hosts: app
  become: true
  vars:
    domain: "{{ '.'.join(inventory_hostname.split('.')[-2:]) }}"
    server_email: "server+{{ inventory_hostname_short }}@{{ domain }}"
    mail_forwarding: "{{ mail_forwarding_json | from_json }}"
  pre_tasks:
    - name: update package cache
      apt:
        # Update apt cache only if it doesn't exist
        cache_valid_time: 31536000
  roles:
    - setup_automatic_updates
    - increase_max_user_watches
    - borgmatic
    - docker
