- name: install nullmailer and bsd-mailx
  apt:
    pkg:
      - nullmailer
      - bsd-mailx
    state: present

- name: configure system mailname
  template:
    src: mailname
    dest: /etc/mailname
    mode: 0644

- name: create nullmailer config directory
  file:
    path: /etc/nullmailer
    state: directory
    mode: 0755

- name: configure default receiving address
  template:
    src: adminaddr
    dest: /etc/nullmailer/adminaddr
    mode: 0644

- name: configure mail forwarding
  template:
    src: remotes
    dest: /etc/nullmailer/remotes
    mode: 0600