- name: find host keys
  find:
    path: "{{ internal_host_key_directory }}"
    pattern: ssh_host_*_key
  register: private_keys
  failed_when: '"matched" not in private_keys or private_keys.matched == 0'
  tags: private_ca

- name: create temporary local directory
  tempfile:
    suffix: integrate_ssh_ca
    state: directory
  changed_when: false
  become: false
  delegate_to: localhost
  register: temporary_directory
  tags: private_ca

- name: fetch public host keys
  fetch:
    src: "{{ item.path }}.pub"
    dest: "{{ temporary_directory.path }}/public_keys/"
  with_items: "{{ private_keys.files }}"
  changed_when: false
  tags: private_ca

- name: fetch existing certificates
  fetch:
    src: "{{ item.path }}-cert.pub"
    dest: "{{ temporary_directory.path }}/existing_certificates/"
    fail_on_missing: false
  with_items: "{{ private_keys.files }}"
  changed_when: false
  tags: private_ca

- name: sign public host keys
  command: ssh-keygen -s {{ ssh_ca_private_key_path | quote }} -I {{ internal_id | quote }} -h -n {{ internal_allowed_hostnames | quote }} {{ temporary_directory.path }}/public_keys/{{ inventory_hostname | quote }}{{ item.path | quote }}.pub
  with_items: "{{ private_keys.files }}"
  delegate_to: localhost
  become: false
  changed_when: false
  tags: private_ca

- name: find generated certificates
  find:
    path: "{{ temporary_directory.path }}/public_keys/{{ inventory_hostname }}{{ internal_host_key_directory }}"
    pattern: ssh_host_*_key-cert.pub
  delegate_to: localhost
  become: false
  register: certificates
  tags: private_ca

- name: diff generated certificates with existing certificates
  shell:
    cmd: diff <(ssh-keygen -L -f {{ item.path | quote }} | tail -n +2) <(ssh-keygen -L -f {{ temporary_directory.path | quote }}/existing_certificates/{{ inventory_hostname | quote }}{{ internal_host_key_directory }}/{{ item.path | basename | quote }} | tail -n +2)
    executable: /bin/bash
  with_items: "{{ certificates.files }}"
  changed_when: false
  failed_when: false
  become: false
  register: certificate_comparison
  tags: private_ca

- name: upload changed certificates
  copy:
    src: "{{ item.item.path }}"
    dest: "{{ internal_host_key_directory }}"
  when: item.rc != 0
  with_items: "{{ certificate_comparison.results }}"
  notify: restart sshd
  tags: private_ca

- name: delete temporary local directory
  file:
    path: "{{ temporary_directory.path }}"
    state: absent
  become: false
  changed_when: false
  tags: private_ca

- name: add sshd configuration for certificates
  lineinfile:
    dest: "{{ internal_config_path }}"
    line: HostCertificate {{ item.path }}-cert.pub
    state: present
    insertafter: HostKey {{ item.path }}
  with_items: "{{ private_keys.files }}"
  notify: restart sshd
  tags: private_ca
