- name: install certbot and cloudflare dns plugin from default repo
  apt:
    pkg:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present

- name: update certbot, cloudflare dns plugin and python3-cloudflare to use testing repo
  apt:
    pkg:
      - certbot
      - python3-certbot-dns-cloudflare
      - python3-cloudflare
    default_release: testing
    update_cache: true
    state: latest
