# Dependencies from https://docs.docker.com/engine/install/debian
- name: install dependencies for docker install
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: add docker repository key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: reload systemd
  systemd:
    name: docker
    state: started
    enabled: true

- name: setup docker config directory
  file:
    path: /etc/docker
    state: directory

# The metrics server IP is hardcoded to be the gateway IP for the docker0 bridge.
# TODO: Is scraping Docker with prometheus needed? Are all the metrics fetchable from cadvisor?
- name: setup docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker
