- name: remove exim config files
  file: path="{{ item }}" state=absent
  with_items:
    - "/etc/exim4/update-exim4.conf.conf"
    - "/etc/mailname"
  listen: reconfigure exim4

- name: generate exim config files
  command: dpkg-reconfigure -f noninteractive exim4-config
  listen: reconfigure exim4

- name: restart exim4
  service:
    name: exim4
    state: restarted
  listen: reconfigure exim4
